# Default values for heytaco-anywhere.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: heytacoanywhere/heytaco-anywhere
  tag: "0.2.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# The keys within the "env" map are mounted as environment variables. 
# See the full reference of Heytaco Anywher environment variables here:
# https://heytaco-anywhere.chat/docs/reference/
#
env:
  # REQUIRED: Set the user-visible hostname.
  #
  HEYTACO_ANYWHERE_SERVER_HOST: ""
  # REQUIRED: The protocol to pair with the value in HEYTACO_ANYWHERE_SERVER_HOST (http or https).
  #
  HEYTACO_ANYWHERE_SERVER_PROTO: https
  # REQUIRED: The secret of Heytaco! app.
  # You can get the secret from https://heytaco.chat/team/apps.
  #
  HEYTACO_ANYWHERE_HEYTACO_APP_SECRET: ""

  # Set the secret that the server validates the signature.
  #
  # HEYTACO_ANYWHERE_WEBHOOK_SECRET:

  # Heytaco Directives (Select Slack or Microsoft Teams)

  # Slack-specific variables.
  #
  HEYTACO_ANYWHERE_SLACK_CHANNEL: ""
  HEYTACO_ANYWHERE_SLACK_CLIENT_ID: ""
  HEYTACO_ANYWHERE_SLACK_CLIENT_SECRET: ""

  # DB-specific vairables.
  # If you are using SQLite as your DB for Heytaco Anywhere, it is recommended to enable persistence.
  #
  # HEYTACO_ANYWHERE_STORE_DRIVER: ""
  # HEYTACO_ANYWHERE_STORE_SOURCE: ""

  # TODO: support Teams

  # Service Directives (Multi service enabled)

  # Github-specific variables.
  #
  # HEYTACO_ANYWHERE_GITHUB_CLIENT_ID: ""
  # HEYTACO_ANYWHERE_GITHUB_CLIENT_SECRET: ""

  # Jira-specific variables.
  #
  # HEYTACO_ANYWHERE_JIRA_CLIENT_ID: ""
  # HEYTACO_ANYWHERE_JIRA_CLIENT_SECRET: ""

  # Confluence-specific variables.
  #
  # HEYTACO_ANYWHERE_CONFLUENCE_CLIENT_ID: ""
  # HEYTACO_ANYWHERE_CONFLUENCE_CLIENT_SECRET: ""

# If you'd like to provide your own Kubernetes Secret object instead of passing your values
# in un-encrypted, pass in the name of a created + populated Secret in the same Namespace
# as the server.
extraSecretNamesForEnvFrom: []
# - heytaco-anywhere-secret

persistentVolume:
  # If you are using SQLite as your DB for Heytaco Anywhere, it is recommended to enable persistence. 
  enabled: true

  accessModes:
    - ReadWriteOnce

  annotations: {}

  existingClaim: ""

  mountPath: /data

  size: 8Gi

  storageClass: ""

  # If empty (the default) or set to null, no volumeBindingMode spec is
  # set, choosing the default mode.
  #
  volumeMode: ""

  subPath: ""

# If persistentVolume.enabled is set to false, it will mount an emptyDir instead of
# a PVC for any state that it needs to persist.
#
emptyDir:
  # Total space to request for the emptyDir. An empty value here means no limit.
  sizeLimit: ""
