kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "heytaco-anywhere.fullname" . }}
  labels:
{{ include "heytaco-anywhere.labels" . | indent 4 }}
data:
{{- range $envKey, $envVal := .Values.env }}
  {{ $envKey | upper }}: {{ $envVal | quote }}
{{- end }}
  
